DELIMITER $$
DROP PROCEDURE IF EXISTS generateIdPenerbit$$
CREATE PROCEDURE generateIdPenerbit(OUT idPenerbit VARCHAR(10))
BEGIN
	DECLARE ctr INT(5);
	DECLARE keluar VARCHAR(10);
	SELECT COUNT(P_ID)+1 INTO ctr FROM publisher;
	SET keluar = CONCAT('P',LPAD(ctr,3,0));
	SET idPenerbit = keluar;
END$$
DELIMITER ;

DELIMITER $$
DROP PROCEDURE IF EXISTS generateIdBC$$
CREATE PROCEDURE generateIdBC(OUT idBC VARCHAR(10))
BEGIN
	DECLARE ctr INT(5);
	DECLARE keluar VARCHAR(10);
	SELECT SUBSTRING(BC_ID,3,4)INTO ctr FROM book_category ORDER BY BC_ID DESC LIMIT 1;
	SET keluar = CONCAT('BC',LPAD(ctr,3,0));
	SET idBC = keluar;
END$$
DELIMITER ;

DELIMITER $$
DROP PROCEDURE IF EXISTS generateIdBook$$
CREATE PROCEDURE generateIdBook(OUT idB VARCHAR(10))
BEGIN
	DECLARE ctr INT(5);
	DECLARE keluar VARCHAR(10);
	SELECT SUBSTRING(B_ID,5,4)INTO ctr FROM book ORDER BY B_ID DESC LIMIT 1;
	SET keluar = CONCAT('BOOK',LPAD(ctr+1,3,0));
	SET idB = keluar;
END$$
DELIMITER ;
